# **PREPARE PROCESSING - CLEANING - SPLITTING**

In [58]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import joblib
from io import StringIO

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split


import warnings

warnings.filterwarnings("ignore")

In [59]:
df = pd.read_csv('diabetes_prediction_dataset.csv')

In [60]:
df_copy = df.copy()

In [61]:
df_copy = df_copy.drop_duplicates(keep='first')
df_copy.head(5)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [62]:
#Mã hóa đặc trưng
le = LabelEncoder()
for col in df_copy.select_dtypes(include=['object']).columns:
    df_copy[col] = le.fit_transform(df_copy[col])

In [63]:
df_copy.head(5)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,4,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0

In [64]:

# Tách X và y
X = df_copy.drop(columns=['diabetes'])
y = df_copy['diabetes']

# Chia tập train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [65]:

scaler = RobustScaler()

X_train_scaled  = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
print(X_train_scaled )

X_test_scaled  = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)
print(X_test_scaled )

       gender       age  hypertension  heart_disease  smoking_history  \
0         1.0  0.485714           0.0            0.0             0.25
1         1.0 -0.428571           0.0            0.0             0.25
2         1.0 -0.342857           0.0            0.0             0.25
3         0.0 -1.142857           0.0            0.0             0.25
4         0.0  0.057143           0.0            1.0            -0.50
...       ...       ...           ...            ...              ...
67297     1.0  0.342857           0.0            0.0             0.00
67298     0.0  0.714286           0.0            0.0             0.50
67299     0.0 -0.457143           0.0            0.0            -0.75
67300     1.0  0.771429           1.0            1.0            -0.75
67301     1.0 -0.400000           0.0            0.0             0.25

            bmi  HbA1c_level  blood_glucose_level
0     -0.255814     0.142857            -0.847458
1     -0.303876    -1.642857             0.338983
2      0.000000     0.285714             1.016949
3     -1.218605    -0.714286             0.254237
4     -1.086822     0.285714            -0.169492
...         ...          ...                  ...
67297  2.060465     1.714286             0.084746
67298  0.000000     0.285714            -0.847458
67299 -1.060465    -1.642857             0.322034
67300  2.175194     0.142857             2.372881
67301 -0.834109     2.285714             1.016949

[67302 rows x 8 columns]
       gender       age  hypertension  heart_disease  smoking_history  \
0         0.0 -0.257143           0.0            0.0            -0.50
1         1.0  0.628571           0.0            0.0            -0.50
2         1.0 -1.193143           0.0            0.0            -0.75
3         1.0 -0.028571           0.0            0.0             0.50
4         1.0 -1.208000           0.0            0.0            -0.75
...       ...       ...           ...            ...              ...
28839     0.0  0.342857           0.0            0.0             0.25
28840     1.0  0.600000           0.0            0.0            -0.75
28841     0.0 -0.628571           0.0            0.0             0.25
28842     1.0 -1.085714           0.0            0.0            -0.75
28843     0.0  0.314286           0.0            0.0             0.25

            bmi  HbA1c_level  blood_glucose_level
0      1.536434    -0.714286             0.254237
1      0.353488    -0.071429             0.000000
2     -1.629457     0.142857            -0.932203
3      0.407752     0.214286             0.000000
4     -1.936434     0.142857             0.000000
...         ...          ...                  ...
28839  0.000000     0.571429            -0.169492
28840  0.000000     0.500000            -0.169492
28841 -1.009302    -0.071429             0.338983
28842  0.000000     0.285714            -1.016949
28843 -1.336434    -1.642857             0.084746

[28844 rows x 8 columns]

In [66]:

# --- Lưu trữ theo cấu trúc của bạn ---
save_dir = "Data_clean"
if not os.path.exists(save_dir):
    os.makedirs(save_dir)
    print(f"Đã tạo thư mục '{save_dir}'")

try:
    # 1. Lưu các tập train/validation để huấn luyện và đánh giá
    np.savez(f'{save_dir}/model_data.npz', 
             X_train=X_train_scaled, X_test=X_test_scaled, 
             y_train=y_train, y_test=y_test)
    print(f"- Đã lưu model_data.npz (chứa X_train, X_validation...) vào '{save_dir}'")

    # 2. Lưu các file CSV đã được làm sạch hoàn chỉnh
    df_copy.to_csv(f'{save_dir}/data_cleaned.csv', index=False)
    print(f"- Đã lưu train_cleaned.csv, test_cleaned.csv vào '{save_dir}'")

    # 3. Lưu bộ xử lý (imputer) đã được huấn luyện
    #joblib.dump(fitted_imputer, f'{save_dir}/imputer.joblib')
    print(f"- Đã lưu imputer.joblib vào '{save_dir}'")

    print("\nNội dung thư mục 'Data_clean':")
    print(os.listdir(save_dir))

except Exception as e:
    print(f"\nLỗi khi lưu file: {e}")

Đã tạo thư mục 'Data_clean'
- Đã lưu model_data.npz (chứa X_train, X_validation...) vào 'Data_clean'
- Đã lưu train_cleaned.csv, test_cleaned.csv vào 'Data_clean'
- Đã lưu imputer.joblib vào 'Data_clean'

Nội dung thư mục 'Data_clean':
['data_cleaned.csv', 'model_data.npz']